apiVersion: v1
kind: Service
metadata:
  name: csharp-kube-service
spec:
  selector:
    app: csharp-img
  ports:
  - protocol: "TCP"
    name: "app"
    port: 6000
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-kube-dep
spec:
  selector:
    matchLabels:
      app: csharp-img
  replicas: 1
  template:
    metadata:
      labels:
        app: csharp-img
    spec:
      containers:
      - name: csharp-img
        image: csharp-img:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80